trigger:
- master

- job: Build513
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 0
  dependsOn:
    - DockerLogin
  steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: DockerHubPublic
  - script: |
      cd build
      echo Starting 5.13 build
      bash --login -c "./generate_qtwasm_image.sh 5.13"
      for t in $(docker images -f "reference=maukalinow/qtwasm_builder:5.1*" --format "{{.Tag}}"); do     docker push maukalinow/qtwasm_builder:${t}; done
    displayName: 'Run 5.13 qt wasm build'

- job: Build514
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 0
  dependsOn:
    - DockerLogin
  steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: DockerHubPublic
  - script: |
      cd build
      echo Starting 5.14 build
      bash --login -c "./generate_qtwasm_image.sh 5.14"
      for t in $(docker images -f "reference=maukalinow/qtwasm_builder:5.1*" --format "{{.Tag}}"); do     docker push maukalinow/qtwasm_builder:${t}; done
    displayName: 'Run 5.14 qt wasm build'
